### ISSUE TITLE
Remaining tasks from GPU release (0.5)

### ISSUE THREAD

**Issue by daurer** [ptycho/ptypy#387]
**Todo for future release:**
- [ ] (Unify logging messages: log(level, message) vs. logger.info, logger.warning, etc.)
- [ ] Make all engines compatible with live processing (#311) -> next release
- [ ] (clean up branches/issues)
- [ ] revisit tests, move to unity-tests, use relevant array sizes. Archive cuda-ext tests. #345
- [ ] archive unused ("testing") kernels #343
- [ ] (automated tests for the gpu part. maybe at NERSC? DLS?)
- [ ] (Check all parameters for userlevel flag and implement accordingly)
- [ ] (merge upsampling PR (#305))

**Comment by bjoernenders** [comment]
All the above comments have been migrated to their own issues with the appropriate labels. closing this.
